openapi: 3.0.3
x-gap-api-metadata:
  ci: smee-user-service API
info:
  title: smee-user-service
  description: 'APIs to manage users across various SMEE apps'
  contact:
    name: SMEE Team
    email: HQ-SMEE-DG@gap.com
  version: '1.0'
servers:
  - url: https://stage.api.azeus.gaptech.com/sourcing/smee-user-service
    description: Stage
  - url: https://api.azeus.gaptech.com/sourcing/smee-user-service
    description: Production
tags:
  - name: smee-user-controller
    description: Smee User Controller
paths:
  /api/user:
    post:
      tags:
        - smee-user-controller
      summary: Create Or Update SMEE User
      operationId: createOrUpdateUserUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SmeeUserCreateResource'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Envelope'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/user/types:
    get:
      tags:
        - smee-user-controller
      summary: Fetch SMEE User Types
      operationId: getUserTypesUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Envelope'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/user/{userId}:
    get:
      tags:
        - smee-user-controller
      summary: Fetch User By GAP AD Id
      operationId: getUserUsingGET
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            example: vprabhu
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Envelope'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: apiKey
  schemas:
    Envelope:
      title: Envelope
      type: object
      properties:
        error:
          type: string
          example: Something Went Wrong!
        httpStatus:
          type: integer
          format: int32
          example: 200
        requestId:
          type: string
          example: b0c6aef4e0769726
        resource:
          $ref: '#/components/schemas/Response'
        resources:
          type: array
          items:
            $ref: '#/components/schemas/SmeeUserTypes'
    Response:
      title: Response
      type: object
    SmeeUserCreateResource:
      title: SmeeUserCreateResource
      required:
        - firstName
        - isActive
        - isVendor
        - lastName
        - userEmail
        - userId
        - userName
        - userType
      type: object
      properties:
        userName:
          maxLength: 20
          minLength: 1
          type: string
          example: vprabhu
        firstName:
          maxLength: 50
          minLength: 1
          type: string
          example: Vinayak
        lastName:
          maxLength: 50
          minLength: 1
          type: string
          example: Prabhu
        userEmail:
          maxLength: 50
          minLength: 1
          type: string
          example: Vinayak_Prabhu@gap.com
        isActive:
          type: boolean
          example: true
        userType:
          maxLength: 20
          minLength: 1
          type: string
          example: GIS PD
        isVendor:
          type: boolean
          example: false
        vendorPartyId:
          type: string
          example: 1000045
        userId:
          maxLength: 10
          minLength: 1
          type: string
          example: dnagpal
    SmeeUserTypes:
      title: SmeeUserTypes
      type: object
      properties:
        description:
          type: string
          example: Asia PD
        name:
          type: string
          example: GIS PD
security:
  - ApiKeyAuth: []
