jdbc:
  primary:
    url: jdbc:sqlserver://localhost:1433;database=smee_user_local
  readOnly:
    url: jdbc:sqlserver://localhost:1433;database=smee_user_local;ApplicationIntent=ReadOnly
  username: smee_user_app
  password: hello-world

smee-user-service:
  denodo-uri: http://denodo.gapinc.com:9090/server/sourcing_db/vendor_relationship/views/vendor_relationship?$format=json&
  apikey: ENC(eWCptjY5A8r+gpHp/FWAbrtO6jpN6HpaicNLvFeMI6CjToOq9CcpkkwPtQBVgJsQ)