server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info, health, env
  endpoint:
    health:
      show-details: always

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
