jdbc:
  primary:
    url: jdbc:sqlserver://localhost:1433;database=smee_user_local
  readOnly:
    url: jdbc:sqlserver://localhost:1433;database=smee_user_local;ApplicationIntent=ReadOnly
  username: smee_user_app
  password: hello-world

smee-user-service:
  vendor-profile-uri: https://stage.api.azeus.gaptech.com/sourcing/vendor-profile-integrator/parties/
  apikey: ENC(JRF/yj8/NGqZr+GHrJqTNHRCgaLplTzM3ZJotF37NtSWuKzR+QxvhXThzby9j5qT)