server:
  port: 8080

spring:
  cache:
    type: caffeine
    cache-names: smee-usertypes
    caffeine:
      spec: maximumSize=500, expireAfterAccess=24h

management:
  endpoints:
    web:
      exposure:
        include: info, health, env
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: false

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
