spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=smee_user_localhost
    username: SA
    password: ENC(gTbq2KQ76FdVkdKdNLxXIvRucctt+HdL)
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver