version: 1-beta
appName: smee-user-service
team: pt-gisbooking
targetEnv: dev
environmentVariables:
  JAVA_NR_OPTS: '-javaagent:/usr/local/newrelic/newrelic.jar'
  NEW_RELIC_APP_NAME: aks-smee-user-service-dev
  NEW_RELIC_LOG: stdout
  NEW_RELIC_LOG_LEVEL: info
  NEW_RELIC_DISTRIBUTED_TRACING: true
  SMEE_CONFIG_SERVER_URL: "https://gisbooking-config-server-configuration.apps.cfplatform.dev.azeus.gaptech.com"
  PROFILE: "development"
secrets:
  secretKeys:
    - key: JASYPT-ENCRYPTOR-PASSWORD
      environmentVariableKey: JASYPT_ENCRYPTOR_PASSWORD
    - key: new-relic-license-key
      environmentVariableKey: NEW_RELIC_LICENSE_KEY
kubernetes:
  dockerImage: gacr2nnonprod.azurecr.io/com/gap/sourcing/smee/smee-user-service
  port: 8080
  #  autoscaling:
  #    minReplicas: 2
  #    maxReplicas: 3
  #    memoryThreshold: 75
  #    cpuThreshold: 75
  resources:
    requestsCpu: 1
    limitsCpu: 2
    requestsMemory: 1G
    limitsMemory: 2G
  health:
    livenessProbe:
      endpoint: /actuator/health/liveness
      port: "8080"
      initialDelay: "25"
      timeout: "600"
      period: "30"
      failureThreshold: "30"
    readinessProbe:
      endpoint: /actuator/health/liveness
      port: "8080"
      initialDelay: "25"
      timeout: "5"
      period: "10"
      failureThreshold: "30"
control:
  destroyApplication: true
