
name: AKS Workflow
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - master
  paths-ignore:
    - 'README.md'
    - 'chartis-stage.yml'

jobs:

  set-short-sha:
    name: Build And Test For AKS
    runs-on: [ self-hosted, arc-dind-rootless-enterprise ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get short sha of the commit
        id: shorten_sha
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
    outputs:
            short_sha: ${{ steps.shorten_sha.outputs.short_sha }}


  docker-build-scan-push:
    needs: set-short-sha
    uses: continuous-delivery-platform/docker-build-scan-push/.github/workflows/docker-build-scan-push.yml@main
    with:
      app-name: smee-user-service
      image-name: com/gap/sourcing/smee/smee-user-service
      image-tag: ${{needs.set-short-sha.outputs.short_sha}}


  deploy-to-dev:
    needs:
      - set-short-sha
      - docker-build-scan-push
    runs-on: [ self-hosted ]
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: Deploy to Dev
        uses: continuous-delivery-platform/chartis-deploy@main
        with:
          chartis-abstract: chartis-dev.yml
          image-tag: ${{needs.set-short-sha.outputs.short_sha}}