name: GIS Booking Merge Workflow

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  merge_pr:
    name: Build when PR is approved
    runs-on: [ self-hosted, arc-dind-rootless-enterprise ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt-hotspot'

      - name: Setup Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Execute Gradle build
        run: ./gradlew build
        env:
          SAAS_ARTIFACTORY_USERNAME: ${{secrets.SAAS_ARTIFACTORY_USERNAME}}
          SAAS_ARTIFACTORY_PASSWORD: ${{secrets.SAAS_ARTIFACTORY_PASSWORD}}
          
      - name: PR is merged
        run: echo "The PR was merged."    
        
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env: 
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          JF_URL: https://gapinc.jfrog.io/
        with:
          download-repository: jfrog-cli
               
      - name: Ping the server
        run: |
          jf rt ping --url=https://gapinc.jfrog.io/artifactory/
      
      - name: Publish Artifact
        env:
          JF_USER: ${{ secrets.JF_USER}}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          FILE_NAME="gis-github-action-workflow-$COMMIT_ID.jar"
          jfrog config add --url=https://gapinc.jfrog.io/ --user=$JF_USER --password=$JF_PASSWORD --interactive=false
          jfrog config show
          jfrog rt u "build/libs/gis-github-action-workflow.jar" "local-non-prod/com/gap/sourcing/smee/gis-github-action-workflow/$COMMIT_ID/$FILE_NAME" --recursive=false
          echo "The artifact $COMMIT_ID is published to JFrog non-prod successfully."

