name: SMEE User Service Promote Workflow

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      artifactID:
        description: 'Enter the artifact id to promote'
        required: true
      appName:
        description: 'provide app name'
        required: true

jobs:
  promote_artifact:
    name: Promote Artifact to Prod
    runs-on: [self-hosted]
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_USER: ${{ secrets.SAAS_ARTIFACTORY_USERNAME }}
          JF_PASSWORD: ${{ secrets.SAAS_ARTIFACTORY_PASSWORD }}
          JF_URL: https://gapinc.jfrog.io/
        with:
          download-repository: jfrog-cli

      - name: Input Artifact ID
        run: |
          echo "Artifact ID: ${{ github.event.inputs.artifactID }}"
           echo "app name ID: ${{ github.event.inputs.appName }}"

      - name: Promote Artifact to Prod
        env:
          JF_USER: ${{ secrets.SAAS_ARTIFACTORY_USERNAME }}
          JF_PASSWORD: ${{ secrets.SAAS_ARTIFACTORY_PASSWORD }}
        run: |
          COMMIT_ID=${{ github.event.inputs.artifactID }}
          APP_NAME=${{ github.event.inputs.appName }}
          FILE_NAME="$APP_NAME-$COMMIT_ID.jar"
          jfrog config add --url=https://gapinc.jfrog.io/ --user=$JF_USER --password=$JF_PASSWORD --interactive=false
          jfrog config show
          jfrog rt cp local-non-prod/com/gap/sourcing/smee/$APP_NAME/$COMMIT_ID/$FILE_NAME local-prod/com/gap/sourcing/smee/$APP_NAME/$COMMIT_ID/$FILE_NAME --flat=true --recursive=false
          echo "The artifact $COMMIT_ID is promoted to JFrog prod successfully."